import { Report } from "../model/reportModel.js";
export async function seedReports() {
  try {
    const reports = [
      {
        reportType: "biasa",
        title: "Kucing terjebak di atap rumah",
        description: "Seekor kucing sudah dua hari tidak turun dari atap.",
        location: {
          lat: -5.147,
          lng: 119.432,
          address: "Jl. Pengayoman No. 12",
        },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Lokasi di Jalan Pengayoman",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Andi Wijaya",
          phone: "081234567801",
          address: "Jl. Pengayoman No. 12",
          rt: "02",
          rw: "06",
          kelurahan: "Panakkukang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Ular masuk ke dalam rumah",
        description: "Terdapat ular piton besar di dapur.",
        location: {
          lat: -5.125,
          lng: 119.448,
          address: "Jl. Toddopuli Raya",
        },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Masuk sekitar pukul 9 malam",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Nurhaliza",
          phone: "081234567802",
          address: "Jl. Toddopuli Raya",
          rt: "01",
          rw: "03",
          kelurahan: "Karampuang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran di rumah makan",
        description: "Terdengar ledakan dari dapur rumah makan.",
        location: {
          lat: -5.14,
          lng: 119.417,
          address: "Jl. Veteran Selatan",
        },
        fireType: "kebakaran_rumah",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Hasanuddin",
          phone: "081234567803",
          address: "Jl. Veteran Selatan",
          rt: "04",
          rw: "02",
          kelurahan: "Maricaya",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "Asap tebal dari rumah tetangga",
        description: "Terlihat asap tebal keluar dari lantai dua.",
        location: {
          lat: -5.137,
          lng: 119.415,
          address: "Jl. Gunung Bawakaraeng",
        },
        fireType: "kebakaran_rumah",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Fitriani",
          phone: "081234567804",
          address: "Jl. Gunung Bawakaraeng",
          rt: "03",
          rw: "01",
          kelurahan: "Maricaya Selatan",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "biasa",
        title: "Orang terjebak di lift",
        description: "Lift macet di lantai 4, ada 2 orang di dalam.",
        location: {
          lat: -5.135,
          lng: 119.427,
          address: "Gedung kantor area Pettarani",
        },
        rescueType: "evakuasi_non_hewan",
        additionalInfo: "Gedung kantor area Pettarani",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Joko Santoso",
          phone: "081234567805",
          address: "Jl. AP Pettarani",
          rt: "02",
          rw: "04",
          kelurahan: "Tidung",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran di bengkel motor",
        description: "Kebakaran diduga karena korsleting listrik.",
        location: {
          lat: -5.138,
          lng: 119.421,
          address: "Jl. Veteran Utara",
        },
        fireType: "kebakaran_bangunan",
        hasCasualties: true,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Ahmad Syahrir",
          phone: "081234567806",
          address: "Jl. Veteran Utara",
          rt: "03",
          rw: "05",
          kelurahan: "Baraya",
          kecamatan: "Bontoala",
        },
      },
      {
        reportType: "biasa",
        title: "Bayi terjebak di kamar mandi",
        description: "Pintu kamar mandi tidak bisa dibuka dari luar.",
        location: {
          lat: -5.136,
          lng: 119.439,
          address: "Jl. Mappanyukki",
        },
        rescueType: "evakuasi_non_hewan",
        additionalInfo: "Perlu bantuan buka pintu cepat",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Dewi Lestari",
          phone: "081234567807",
          address: "Jl. Mappanyukki",
          rt: "01",
          rw: "07",
          kelurahan: "Kunjung Mae",
          kecamatan: "Mariso",
        },
      },
      {
        reportType: "darurat",
        title: "Mobil terbakar di jalan raya",
        description: "Mobil terbakar di lampu merah Pettarani.",
        location: {
          lat: -5.133,
          lng: 119.445,
          address: "Jl. Pettarani",
        },
        fireType: "kebakaran_kendaraan",
        hasCasualties: false,
        urgencyLevel: "sedang",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Rahmat Hidayat",
          phone: "081234567808",
          address: "Jl. Pettarani No. 5",
          rt: "04",
          rw: "02",
          kelurahan: "Banta-Bantaeng",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "biasa",
        title: "Anak tersangkut di pohon",
        description: "Anak panjat pohon mangga, tidak bisa turun.",
        location: {
          lat: -5.149,
          lng: 119.438,
          address: "Jl. Abdullah Daeng Sirua",
        },
        rescueType: "evakuasi_non_hewan",
        additionalInfo: "Tinggi sekitar 4 meter",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Lukman Hakim",
          phone: "081234567809",
          address: "Jl. Abdullah Daeng Sirua",
          rt: "03",
          rw: "03",
          kelurahan: "Tamamaung",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Rumah terbakar di kompleks BTN",
        description: "Api cepat menyebar karena banyak bahan mudah terbakar.",
        location: {
          lat: -5.143,
          lng: 119.429,
          address: "Jl. Daeng Tata",
        },
        fireType: "kebakaran_rumah",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Siti Nurhaliza",
          phone: "081234567810",
          address: "Jl. Daeng Tata",
          rt: "05",
          rw: "01",
          kelurahan: "Parangtambung",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran di SPBU",
        description: "Asap tebal keluar dari dispenser SPBU.",
        location: {
          lat: -5.15,
          lng: 119.42,
          address: "Jl. Perintis Kemerdekaan No.45",
        },
        fireType: "spbu",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Rizky Ramadhan",
          phone: "081234567811",
          address: "Jl. Perintis No.10",
          rt: "01",
          rw: "02",
          kelurahan: "Tamalanrea Indah",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "darurat",
        title: "Pabrik terbakar",
        description: "Api besar terlihat dari bagian produksi.",
        location: { lat: -5.153, lng: 119.43, address: "Jl. Industri No.77" },
        fireType: "pabrik_industri",
        hasCasualties: true,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Sinta Maulida",
          phone: "081234567812",
          address: "Jl. Industri 2",
          rt: "02",
          rw: "04",
          kelurahan: "Biring Romang",
          kecamatan: "Manggala",
        },
      },
      {
        reportType: "biasa",
        title: "Evakuasi kucing liar",
        description: "Kucing terjebak di gorong-gorong depan rumah.",
        location: {
          lat: -5.142,
          lng: 119.428,
          address: "Jl. Cendrawasih No. 21",
        },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Terdengar suara mengeong sejak pagi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Andini Larasati",
          phone: "081234567813",
          address: "Jl. Cendrawasih No. 21",
          rt: "03",
          rw: "05",
          kelurahan: "Mariso",
          kecamatan: "Mariso",
        },
      },
      {
        reportType: "darurat",
        title: "Pasar tradisional terbakar",
        description: "Beberapa kios di pasar mulai terbakar.",
        location: {
          lat: -5.139,
          lng: 119.435,
          address: "Pasar Sentral Makassar",
        },
        fireType: "pasar",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Fahmi Zain",
          phone: "081234567814",
          address: "Jl. Bandang No. 19",
          rt: "04",
          rw: "01",
          kelurahan: "Buloa",
          kecamatan: "Tallo",
        },
      },
      {
        reportType: "biasa",
        title: "Pohon tumbang blokir jalan",
        description: "Pohon besar tumbang akibat hujan deras.",
        location: { lat: -5.13, lng: 119.437, address: "Jl. Urip Sumoharjo" },
        rescueType:
          "kebakaran_layanan_lingkungan_dan_fasilitas_umum_penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Menghalangi dua jalur utama",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Iwan Darmawan",
          phone: "081234567815",
          address: "Jl. Urip Sumoharjo No. 34",
          rt: "02",
          rw: "02",
          kelurahan: "Panaikang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Gudang logistik terbakar",
        description: "Api membesar cepat dari belakang gudang.",
        location: { lat: -5.147, lng: 119.423, address: "Jl. Kima Raya" },
        fireType: "gudang",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Yusuf Rahman",
          phone: "081234567816",
          address: "Jl. Kima Utara No. 8",
          rt: "03",
          rw: "06",
          kelurahan: "Daya",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Burung hantu nyasar ke rumah",
        description: "Burung hantu masuk dan tidak mau keluar.",
        location: { lat: -5.148, lng: 119.44, address: "Jl. Dg Tata 2" },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Anak-anak takut karena bunyinya",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Nina Amelia",
          phone: "081234567817",
          address: "Jl. Dg Tata 2 No. 7",
          rt: "01",
          rw: "01",
          kelurahan: "Parangtambung",
          kecamatan: "Tamalate",
        },
      },
      {
        reportType: "darurat",
        title: "Gedung perkantoran terbakar",
        description: "Asap keluar dari lantai 5 gedung.",
        location: { lat: -5.145, lng: 119.425, address: "Jl. AP Pettarani" },
        fireType: "gedung_bertingkat",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Dedi Irawan",
          phone: "081234567818",
          address: "Jl. Pettarani No. 50",
          rt: "05",
          rw: "03",
          kelurahan: "Buakana",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "biasa",
        title: "Sapi lepas di jalan utama",
        description: "Sapi besar lepas dan mengganggu lalu lintas.",
        location: { lat: -5.146, lng: 119.438, address: "Jl. Sultan Alauddin" },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Berada di jalur tengah jalan raya",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Arman Sudirman",
          phone: "081234567819",
          address: "Jl. Sultan Alauddin No. 9",
          rt: "03",
          rw: "04",
          kelurahan: "Maccini Sombala",
          kecamatan: "Tamalate",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran lahan kosong",
        description: "Lahan dekat perumahan mulai terbakar.",
        location: {
          lat: -5.144,
          lng: 119.433,
          address: "Jl. Bumi Tamalanrea Permai",
        },
        fireType: "hutan_lahan",
        hasCasualties: false,
        urgencyLevel: "sedang",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/n654a4ecvu1bqdvuogil.jpg",
        reporterInfo: {
          name: "Sri Wahyuni",
          phone: "081234567820",
          address: "Jl. BTP Blok D",
          rt: "02",
          rw: "05",
          kelurahan: "Tamalanrea Jaya",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran rumah tinggal",
        description: "Api terlihat dari dapur rumah warga.",
        location: { lat: -5.139, lng: 119.412, address: "Jl. Pongtiku" },
        fireType: "rumah_tinggal",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire1.jpg",
        reporterInfo: {
          name: "Rudi Hartono",
          phone: "081234567821",
          address: "Jl. Pongtiku No. 21",
          rt: "04",
          rw: "02",
          kelurahan: "Bontoala",
          kecamatan: "Bontoala",
        },
      },
      {
        reportType: "biasa",
        title: "Anjing terjebak di gorong-gorong",
        description: "Suara lolongan terdengar dari dalam saluran air.",
        location: { lat: -5.153, lng: 119.435, address: "Jl. Urip Sumoharjo" },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga sudah mencoba menolong tapi gagal.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue1.jpg",
        reporterInfo: {
          name: "Linda Marpaung",
          phone: "081234567822",
          address: "Jl. Urip Sumoharjo No. 45",
          rt: "06",
          rw: "01",
          kelurahan: "Karampuang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "SPBU terbakar",
        description: "Ledakan terdengar dari pompa bensin.",
        location: {
          lat: -5.15,
          lng: 119.417,
          address: "Jl. Perintis Kemerdekaan",
        },
        fireType: "spbu",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire2.jpg",
        reporterInfo: {
          name: "Ari Syahputra",
          phone: "081234567823",
          address: "Jl. Perintis No. 10",
          rt: "08",
          rw: "03",
          kelurahan: "Tamalanrea",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Ular masuk rumah",
        description: "Ular bersembunyi di kolong lemari dapur.",
        location: { lat: -5.155, lng: 119.421, address: "Jl. Cendrawasih" },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga takut mendekat.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue2.jpg",
        reporterInfo: {
          name: "Nuraeni",
          phone: "081234567824",
          address: "Jl. Cendrawasih No. 12",
          rt: "02",
          rw: "06",
          kelurahan: "Lajangiru",
          kecamatan: "Ujung Pandang",
        },
      },
      {
        reportType: "darurat",
        title: "Pasar tradisional terbakar",
        description: "Beberapa kios terbakar, asap tebal menyelimuti area.",
        location: { lat: -5.14, lng: 119.426, address: "Pasar Terong" },
        fireType: "pasar",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire3.jpg",
        reporterInfo: {
          name: "Hasan Basri",
          phone: "081234567825",
          address: "Jl. Veteran Selatan",
          rt: "07",
          rw: "04",
          kelurahan: "Maradekaya Selatan",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "biasa",
        title: "Pohon tumbang menutup jalan",
        description: "Pohon besar tumbang dan menghalangi lalu lintas.",
        location: { lat: -5.149, lng: 119.422, address: "Jl. Hertasning" },
        rescueType:
          "kebakaran_layanan_lingkungan_dan_fasilitas_umum_penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Membahayakan pengendara motor.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue3.jpg",
        reporterInfo: {
          name: "Ida Farida",
          phone: "081234567826",
          address: "Jl. Hertasning No. 19",
          rt: "03",
          rw: "02",
          kelurahan: "Karunrung",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran gudang bahan kimia",
        description: "Asap berwarna hitam pekat dan bau menyengat.",
        location: { lat: -5.143, lng: 119.437, address: "Jl. Kima Raya" },
        fireType: "gudang",
        hasCasualties: false,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire4.jpg",
        reporterInfo: {
          name: "Yusuf Ramli",
          phone: "081234567827",
          address: "Jl. Kima Raya No. 30",
          rt: "05",
          rw: "05",
          kelurahan: "Bira",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Kucing terjebak di atap",
        description: "Kucing tidak bisa turun dari atap rumah tetangga.",
        location: { lat: -5.152, lng: 119.419, address: "Jl. Veteran Utara" },
        rescueType: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Sudah dua hari tidak turun.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue4.jpg",
        reporterInfo: {
          name: "Siti Aminah",
          phone: "081234567828",
          address: "Jl. Veteran Utara No. 16",
          rt: "09",
          rw: "01",
          kelurahan: "Maccini",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "Pabrik terbakar di kawasan industri",
        description: "Api besar terlihat dari dalam kompleks.",
        location: {
          lat: -5.141,
          lng: 119.428,
          address: "Kawasan Industri Makassar",
        },
        fireType: "pabrik_industri",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire5.jpg",
        reporterInfo: {
          name: "Taufik Rahman",
          phone: "081234567829",
          address: "Jl. KIMA Blok C",
          rt: "01",
          rw: "01",
          kelurahan: "Bira",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Pipa bocor dan air menyembur",
        description: "Air membanjiri jalan sekitar lokasi.",
        location: { lat: -5.142, lng: 119.431, address: "Jl. Daeng Ramang" },
        rescueType:
          "kebakaran_layanan_lingkungan_dan_fasilitas_umum_penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Warga sulit melintas karena genangan air.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue5.jpg",
        reporterInfo: {
          name: "Rahmat Hidayat",
          phone: "081234567830",
          address: "Jl. Daeng Ramang No. 3",
          rt: "02",
          rw: "04",
          kelurahan: "Sudiang Raya",
          kecamatan: "Biringkanaya",
        },
      },
    ];
    for (const report of reports) {
      const exist = await Report.findOne({
        title: report.title,
        "location.address": report.location.address,
      });
      if (exist) {
        console.log(`Report with title "${report.title}" already exists.`);
        continue;
      }
      const newReport = new Report({
        ...report,
      });
      await newReport.save();
      console.log("Reports seeded successfully");
    }
  } catch (error) {
    console.error("Error seeding reports:", error);
  }
}
