import { Report } from "../model/reportModel.js";
export async function seedReports() {
  try {
    const reports = [
      {
        reportType: "darurat",
        title: "Gudang meledak di pelabuhan",
        description: "Asap dan api terlihat dari dalam gudang.",
        location: { lat: -5.133, lng: 119.41, address: "Jl. Nusantara Baru" },
        fireType: "gudang",
        hasCasualties: true,
        urgencyLevel: "kritis",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire1.jpg",
        reporterInfo: {
          name: "Andi Faisal",
          phone: "081234567831",
          address: "Jl. Nusantara No. 22",
          rt: "03",
          rw: "02",
          kelurahan: "Tamalabba",
          kecamatan: "Ujung Tanah",
        },
      },
      {
        reportType: "biasa",
        title: "Kucing jatuh ke dalam sumur",
        description: "Terdengar suara dari dalam sumur sejak pagi.",
        location: {
          lat: -5.145,
          lng: 119.417,
          address: "Jl. Gunung Bawakaraeng",
        },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Butuh bantuan untuk mengangkatnya.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue1.jpg",
        reporterInfo: {
          name: "Nurul Azmi",
          phone: "081234567832",
          address: "Jl. Gunung Bawakaraeng No. 5",
          rt: "04",
          rw: "03",
          kelurahan: "Maradekaya",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "SPBU terbakar saat pengisian bahan bakar",
        description: "Api tiba-tiba muncul di pompa nomor 4.",
        location: {
          lat: -5.154,
          lng: 119.421,
          address: "Jl. Perintis Kemerdekaan",
        },
        fireType: "spbu",
        hasCasualties: true,
        urgencyLevel: "tinggi",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire2.jpg",
        reporterInfo: {
          name: "Yusuf Hasyim",
          phone: "081234567833",
          address: "Jl. Perintis Kemerdekaan No. 101",
          rt: "07",
          rw: "03",
          kelurahan: "Daya",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Kambing terperosok ke got besar",
        description: "Hewan peliharaan jatuh ke dalam selokan.",
        location: {
          lat: -5.151,
          lng: 119.425,
          address: "Jl. Abdullah Daeng Sirua",
        },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Tidak bisa keluar sendiri.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue2.jpg",
        reporterInfo: {
          name: "Mardiana",
          phone: "081234567834",
          address: "Jl. A.D. Sirua No. 14",
          rt: "06",
          rw: "02",
          kelurahan: "Pampang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Mobil terbakar di tengah jalan",
        description: "Asap keluar dari kap mesin dan meledak.",
        location: { lat: -5.14, lng: 119.423, address: "Jl. AP Pettarani" },
        fireType: "kendaraan",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire3.jpg",
        reporterInfo: {
          name: "Ridwan Malik",
          phone: "081234567835",
          address: "Jl. AP Pettarani No. 98",
          rt: "01",
          rw: "01",
          kelurahan: "Buakana",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "biasa",
        title: "Tiang listrik miring dan nyaris tumbang",
        description: "Bisa membahayakan warga sekitar.",
        location: { lat: -5.157, lng: 119.418, address: "Jl. Barukang" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Segera butuh penanganan.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue3.jpg",
        reporterInfo: {
          name: "Sri Wahyuni",
          phone: "081234567836",
          address: "Jl. Barukang No. 10",
          rt: "02",
          rw: "02",
          kelurahan: "Tamalabba",
          kecamatan: "Ujung Tanah",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran rumah tinggal akibat korsleting",
        description: "Api menyebar cepat ke rumah tetangga.",
        location: { lat: -5.143, lng: 119.415, address: "Jl. Rajawali" },
        fireType: "rumah_tinggal",
        hasCasualties: true,
        urgencyLevel: "kritis",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire4.jpg",
        reporterInfo: {
          name: "Zulkifli",
          phone: "081234567837",
          address: "Jl. Rajawali No. 8",
          rt: "05",
          rw: "05",
          kelurahan: "Pannampu",
          kecamatan: "Tallo",
        },
      },
      {
        reportType: "biasa",
        title: "Biawak masuk ke dalam rumah warga",
        description: "Warga takut mendekat.",
        location: { lat: -5.135, lng: 119.416, address: "Jl. Monginsidi" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Biawak sembunyi di bawah lemari.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue4.jpg",
        reporterInfo: {
          name: "Lukman Hakim",
          phone: "081234567838",
          address: "Jl. Monginsidi No. 3",
          rt: "04",
          rw: "01",
          kelurahan: "Karang Anyar",
          kecamatan: "Mamajang",
        },
      },
      {
        reportType: "darurat",
        title: "Pasar tradisional terbakar saat dini hari",
        description: "Lapak pedagang habis terbakar.",
        location: {
          lat: -5.147,
          lng: 119.427,
          address: "Pasar Sentral Makassar",
        },
        fireType: "pasar",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire5.jpg",
        reporterInfo: {
          name: "Rahmawati",
          phone: "081234567839",
          address: "Jl. Somba Opu No. 27",
          rt: "08",
          rw: "04",
          kelurahan: "Wajo",
          kecamatan: "Wajo",
        },
      },
      {
        reportType: "biasa",
        title: "Pohon tumbang menutup jalan utama",
        description: "Jalan tidak bisa dilalui kendaraan.",
        location: { lat: -5.136, lng: 119.412, address: "Jl. Hertasning" },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Butuh alat berat untuk evakuasi pohon.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue5.jpg",
        reporterInfo: {
          name: "Samsul Bahri",
          phone: "081234567840",
          address: "Jl. Hertasning No. 6",
          rt: "03",
          rw: "03",
          kelurahan: "Karunrung",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran di ruko pasar malam",
        description: "Api cepat membesar dan membakar 3 ruko.",
        location: { lat: -5.129, lng: 119.428, address: "Jl. Cendrawasih" },
        fireType: "ruko_toko",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire6.jpg",
        reporterInfo: {
          name: "Andi Sulaiman",
          phone: "081234567841",
          address: "Jl. Cendrawasih No. 10",
          rt: "02",
          rw: "01",
          kelurahan: "Mariso",
          kecamatan: "Mariso",
        },
      },
      {
        reportType: "biasa",
        title: "Ular masuk ke dapur warga",
        description: "Ular berukuran besar ditemukan di dekat kompor.",
        location: { lat: -5.139, lng: 119.424, address: "Jl. Toddopuli Raya" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Masih bersembunyi di belakang lemari.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue6.jpg",
        reporterInfo: {
          name: "Fitriani",
          phone: "081234567842",
          address: "Jl. Toddopuli Raya No. 20",
          rt: "05",
          rw: "03",
          kelurahan: "Borong",
          kecamatan: "Manggala",
        },
      },
      {
        reportType: "darurat",
        title: "Gedung perkantoran terbakar",
        description: "Asap tebal keluar dari lantai 3.",
        location: { lat: -5.13, lng: 119.419, address: "Jl. Urip Sumoharjo" },
        fireType: "gedung_bertingkat",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire7.jpg",
        reporterInfo: {
          name: "Fadli Rahman",
          phone: "081234567843",
          address: "Jl. Urip Sumoharjo No. 14",
          rt: "06",
          rw: "02",
          kelurahan: "Panaikang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Sapi peliharaan lepas dan mengamuk",
        description: "Mengganggu kendaraan di jalan raya.",
        location: { lat: -5.137, lng: 119.418, address: "Jl. Sultan Alauddin" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Butuh petugas untuk menenangkan dan evakuasi.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue7.jpg",
        reporterInfo: {
          name: "Wahyudi",
          phone: "081234567844",
          address: "Jl. Sultan Alauddin No. 9",
          rt: "01",
          rw: "01",
          kelurahan: "Maccini Sombala",
          kecamatan: "Tamalate",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran hutan kecil di pinggir kota",
        description: "Api menjalar ke arah pemukiman.",
        location: { lat: -5.162, lng: 119.439, address: "Jl. Lingkar Selatan" },
        fireType: "hutan_lahan",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire8.jpg",
        reporterInfo: {
          name: "Hasnidar",
          phone: "081234567845",
          address: "Jl. Lingkar Selatan No. 1",
          rt: "03",
          rw: "04",
          kelurahan: "Parangtambung",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Jalan rusak parah dan menyebabkan banjir",
        description: "Air tergenang karena saluran tersumbat.",
        location: { lat: -5.149, lng: 119.413, address: "Jl. Landak" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Warga sudah coba bersihkan saluran.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue8.jpg",
        reporterInfo: {
          name: "Nurhayati",
          phone: "081234567846",
          address: "Jl. Landak No. 11",
          rt: "02",
          rw: "03",
          kelurahan: "Bontoala",
          kecamatan: "Bontoala",
        },
      },
      {
        reportType: "darurat",
        title: "Tanker minyak meledak di pelabuhan",
        description: "Ledakan terdengar hingga radius 3 km.",
        location: {
          lat: -5.132,
          lng: 119.425,
          address: "Pelabuhan Soekarno Hatta",
        },
        fireType: "lainnya",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire9.jpg",
        reporterInfo: {
          name: "Muh. Arsyad",
          phone: "081234567847",
          address: "Jl. Nusantara Lama No. 8",
          rt: "04",
          rw: "02",
          kelurahan: "Pattunuang",
          kecamatan: "Wajo",
        },
      },
      {
        reportType: "biasa",
        title: "Kucing terjebak di atas tiang listrik",
        description: "Sudah dua jam tidak turun.",
        location: { lat: -5.144, lng: 119.414, address: "Jl. Kakatua" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga takut kucing tersetrum.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue9.jpg",
        reporterInfo: {
          name: "Hj. Munira",
          phone: "081234567848",
          address: "Jl. Kakatua No. 5",
          rt: "06",
          rw: "03",
          kelurahan: "Maccini Parang",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "Pabrik kimia terbakar dan timbulkan asap beracun",
        description: "Warga dievakuasi dari sekitar lokasi.",
        location: {
          lat: -5.155,
          lng: 119.429,
          address: "Jl. Industri Makassar",
        },
        fireType: "pabrik_industri",
        hasCasualties: true,
        urgencyLevel: "kritis",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire10.jpg",
        reporterInfo: {
          name: "Budi Santoso",
          phone: "081234567849",
          address: "Jl. Industri No. 3",
          rt: "02",
          rw: "01",
          kelurahan: "Kima",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Tiang reklame nyaris roboh",
        description: "Besi penyangga tampak lepas.",
        location: { lat: -5.142, lng: 119.42, address: "Jl. Pengayoman" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Bisa menimpa pengendara yang lewat.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue10.jpg",
        reporterInfo: {
          name: "Indah Ramadhani",
          phone: "081234567850",
          address: "Jl. Pengayoman No. 18",
          rt: "03",
          rw: "04",
          kelurahan: "Masale",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Kucing terjebak di loteng rumah kosong",
        description: "Terdengar suara mengeong dari dalam rumah.",
        location: { lat: -5.14, lng: 119.419, address: "Jl. Cendrawasih" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga tidak berani membuka paksa rumah.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue16.jpg",
        reporterInfo: {
          name: "Nadira Aulia",
          phone: "081234567861",
          address: "Jl. Cendrawasih No. 11",
          rt: "02",
          rw: "03",
          kelurahan: "Bontoala",
          kecamatan: "Bontoala",
        },
      },
      {
        reportType: "biasa",
        title: "Pohon tumbang tutupi jalan",
        description: "Pohon besar tumbang menutupi akses utama warga.",
        location: { lat: -5.144, lng: 119.424, address: "Jl. Monginsidi" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Membahayakan pengendara.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue17.jpg",
        reporterInfo: {
          name: "Arsyad Malik",
          phone: "081234567862",
          address: "Jl. Monginsidi No. 24",
          rt: "05",
          rw: "02",
          kelurahan: "Losari",
          kecamatan: "Ujung Pandang",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran di rumah kontrakan",
        description: "Api berasal dari korsleting listrik.",
        location: { lat: -5.13, lng: 119.434, address: "Jl. Aroepala" },
        fireType: "rumah_tinggal",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire16.jpg",
        reporterInfo: {
          name: "Sahrul Baso",
          phone: "081234567863",
          address: "Jl. Aroepala No. 9",
          rt: "03",
          rw: "01",
          kelurahan: "Karunrung",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "biasa",
        title: "Bayi terkunci di dalam mobil",
        description: "Kunci mobil tertinggal di dalam.",
        location: { lat: -5.135, lng: 119.427, address: "Jl. Hertasning" },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Ibu panik dan butuh bantuan cepat.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue18.jpg",
        reporterInfo: {
          name: "Desy Marlina",
          phone: "081234567864",
          address: "Jl. Hertasning No. 17",
          rt: "04",
          rw: "03",
          kelurahan: "Buakana",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "darurat",
        title: "Api melahap gudang tekstil",
        description: "Terdengar suara ledakan dari dalam gudang.",
        location: { lat: -5.122, lng: 119.438, address: "Jl. Kima Raya" },
        fireType: "gudang",
        hasCasualties: true,
        urgencyLevel: "kritis",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire17.jpg",
        reporterInfo: {
          name: "Hendra Gunawan",
          phone: "081234567865",
          address: "Jl. Kima Raya No. 45",
          rt: "06",
          rw: "01",
          kelurahan: "Daya",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Sapi lepas dari kandang",
        description: "Sapi berlarian di area perumahan warga.",
        location: { lat: -5.151, lng: 119.422, address: "Jl. Toddopuli" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga khawatir terjadi kecelakaan.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue19.jpg",
        reporterInfo: {
          name: "Muhlis Abdi",
          phone: "081234567866",
          address: "Jl. Toddopuli No. 7",
          rt: "02",
          rw: "04",
          kelurahan: "Paropo",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Kios pasar terbakar malam hari",
        description: "Api menyebar dengan cepat di area pasar.",
        location: { lat: -5.138, lng: 119.431, address: "Pasar Terong" },
        fireType: "pasar",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire18.jpg",
        reporterInfo: {
          name: "Nurdin Halim",
          phone: "081234567867",
          address: "Jl. Veteran Timur No. 3",
          rt: "01",
          rw: "01",
          kelurahan: "Maradekaya",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "biasa",
        title: "Pipa air bocor dan semprotkan air ke jalan",
        description: "Jalan licin dan membahayakan pengendara.",
        location: { lat: -5.125, lng: 119.42, address: "Jl. Urip Sumoharjo" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Kondisi sudah berlangsung sejak subuh.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue20.jpg",
        reporterInfo: {
          name: "Sitti Aminah",
          phone: "081234567868",
          address: "Jl. Urip Sumoharjo No. 12",
          rt: "02",
          rw: "03",
          kelurahan: "Tello Baru",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Bocah jatuh ke selokan sempit",
        description: "Selokan terlalu sempit untuk dijangkau warga.",
        location: {
          lat: -5.132,
          lng: 119.429,
          address: "Jl. Abdullah Daeng Sirua",
        },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Butuh alat bantu khusus.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue21.jpg",
        reporterInfo: {
          name: "Ahmad Rizal",
          phone: "081234567869",
          address: "Jl. A. Dg Sirua No. 14",
          rt: "04",
          rw: "02",
          kelurahan: "Karampuang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran kendaraan di parkiran ruko",
        description: "Mobil terbakar saat mesin dinyalakan.",
        location: {
          lat: -5.148,
          lng: 119.413,
          address: "Jl. Gunung Bawakaraeng",
        },
        fireType: "kendaraan",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire19.jpg",
        reporterInfo: {
          name: "Tasya Lestari",
          phone: "081234567870",
          address: "Jl. Gunung Bawakaraeng No. 15",
          rt: "01",
          rw: "02",
          kelurahan: "Gaddong",
          kecamatan: "Bontoala",
        },
      },
      {
        reportType: "biasa",
        title: "Kucing terjebak di saluran air",
        description: "Terdengar suara kucing dari dalam saluran.",
        location: {
          lat: -5.151,
          lng: 119.43,
          address: "Jl. Abdullah Dg. Sirua",
        },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Sulit dijangkau tanpa alat khusus.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue22.jpg",
        reporterInfo: {
          name: "Irmawati",
          phone: "081234567871",
          address: "Jl. Dg. Sirua No. 9",
          rt: "01",
          rw: "02",
          kelurahan: "Paropo",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Gudang penyimpanan terbakar",
        description: "Asap pekat terlihat dari luar gedung.",
        location: { lat: -5.124, lng: 119.432, address: "Jl. Kima 10" },
        fireType: "gudang",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire20.jpg",
        reporterInfo: {
          name: "Farhan Yusuf",
          phone: "081234567872",
          address: "Jl. Kima 8 Blok D",
          rt: "03",
          rw: "01",
          kelurahan: "Daya",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Pohon tumbang menimpa kabel listrik",
        description: "Warga khawatir terjadi korsleting.",
        location: { lat: -5.137, lng: 119.415, address: "Jl. Andalas" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Kabel masih aktif dan bertegangan.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue23.jpg",
        reporterInfo: {
          name: "Husna Nur",
          phone: "081234567873",
          address: "Jl. Andalas No. 17",
          rt: "02",
          rw: "04",
          kelurahan: "Maricaya",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "SPBU terbakar setelah pengisian BBM",
        description: "Kebakaran diduga akibat percikan api dari kendaraan.",
        location: {
          lat: -5.141,
          lng: 119.438,
          address: "Jl. Perintis Kemerdekaan",
        },
        fireType: "spbu",
        hasCasualties: true,
        urgencyLevel: "kritis",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire21.jpg",
        reporterInfo: {
          name: "Aditya Permana",
          phone: "081234567874",
          address: "Jl. Perintis Blok G",
          rt: "01",
          rw: "02",
          kelurahan: "Tamalanrea Indah",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Anak kecil terjebak di lift rusak",
        description: "Lift berhenti mendadak di lantai 3.",
        location: { lat: -5.128, lng: 119.421, address: "Jl. Pelita Raya" },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Anak panik dan menangis.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue24.jpg",
        reporterInfo: {
          name: "Lina Sari",
          phone: "081234567875",
          address: "Jl. Pelita No. 5",
          rt: "02",
          rw: "03",
          kelurahan: "Tidung",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "biasa",
        title: "Bangkai kucing di got depan rumah",
        description: "Menimbulkan bau tidak sedap.",
        location: { lat: -5.134, lng: 119.417, address: "Jl. Veteran Selatan" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Sudah lebih dari 2 hari belum diangkat.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue25.jpg",
        reporterInfo: {
          name: "Dwi Pratiwi",
          phone: "081234567876",
          address: "Jl. Veteran Selatan No. 3",
          rt: "04",
          rw: "01",
          kelurahan: "Karang Anyar",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran ruko 3 lantai di tengah kota",
        description: "Api menjalar ke lantai atas dengan cepat.",
        location: { lat: -5.147, lng: 119.436, address: "Jl. AP Pettarani" },
        fireType: "ruko_toko",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire22.jpg",
        reporterInfo: {
          name: "Rizky Maulana",
          phone: "081234567877",
          address: "Jl. Pettarani No. 15",
          rt: "03",
          rw: "02",
          kelurahan: "Sinrijala",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Ular masuk ke dalam rumah warga",
        description: "Ular terlihat bersembunyi di bawah lemari.",
        location: { lat: -5.126, lng: 119.416, address: "Jl. Barukang" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga ketakutan, tidak berani mendekat.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue26.jpg",
        reporterInfo: {
          name: "Agus Ramli",
          phone: "081234567878",
          address: "Jl. Barukang No. 22",
          rt: "01",
          rw: "03",
          kelurahan: "Ujung Tanah",
          kecamatan: "Ujung Tanah",
        },
      },
      {
        reportType: "biasa",
        title: "Selokan mampet dan air meluap ke jalan",
        description: "Air selokan naik ke permukaan saat hujan.",
        location: { lat: -5.131, lng: 119.42, address: "Jl. Dg. Tata" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Mengganggu lalu lintas dan pejalan kaki.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue27.jpg",
        reporterInfo: {
          name: "Nur Fadilah",
          phone: "081234567879",
          address: "Jl. Dg. Tata No. 8",
          rt: "04",
          rw: "02",
          kelurahan: "Parang Tambung",
          kecamatan: "Tamalate",
        },
      },
      {
        reportType: "darurat",
        title: "Mobil terbakar di area parkir kampus",
        description: "Mobil mendadak terbakar saat dipanaskan.",
        location: { lat: -5.143, lng: 119.412, address: "Jl. Perintis Km 10" },
        fireType: "kendaraan",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire23.jpg",
        reporterInfo: {
          name: "Alfiansyah",
          phone: "081234567880",
          address: "Jl. Perintis Blok A",
          rt: "02",
          rw: "01",
          kelurahan: "Bira",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Anjing terjebak di parit",
        description: "Anjing tidak bisa naik dari parit yang dalam.",
        location: { lat: -5.149, lng: 119.437, address: "Jl. Daeng Tata 2" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Sudah berada di sana selama beberapa jam.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue28.jpg",
        reporterInfo: {
          name: "Fitriani",
          phone: "081234567881",
          address: "Jl. Daeng Tata 2 No. 7",
          rt: "03",
          rw: "02",
          kelurahan: "Maccini Parang",
          kecamatan: "Makassar",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran rumah warga di Antang",
        description: "Api muncul dari dapur dan menyebar cepat.",
        location: { lat: -5.15, lng: 119.441, address: "Jl. Antang Raya" },
        fireType: "rumah_tinggal",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire24.jpg",
        reporterInfo: {
          name: "Andi Mappiare",
          phone: "081234567882",
          address: "Jl. Antang Blok H",
          rt: "04",
          rw: "01",
          kelurahan: "Antang",
          kecamatan: "Manggala",
        },
      },
      {
        reportType: "biasa",
        title: "Tiang listrik miring hampir roboh",
        description: "Dikhawatirkan dapat menimpa kendaraan yang lewat.",
        location: { lat: -5.144, lng: 119.426, address: "Jl. Hertasning" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Kondisi sudah seperti ini selama dua hari.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue29.jpg",
        reporterInfo: {
          name: "Yusuf Ismail",
          phone: "081234567883",
          address: "Jl. Hertasning No. 11",
          rt: "02",
          rw: "03",
          kelurahan: "Karunrung",
          kecamatan: "Rappocini",
        },
      },
      {
        reportType: "darurat",
        title: "Mobil terbakar di jalan tol",
        description: "Mobil mengeluarkan asap lalu terbakar.",
        location: { lat: -5.139, lng: 119.439, address: "Jalan Tol Reformasi" },
        fireType: "kendaraan",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire25.jpg",
        reporterInfo: {
          name: "Rina Maulida",
          phone: "081234567884",
          address: "Jl. Urip Sumoharjo No. 8",
          rt: "01",
          rw: "04",
          kelurahan: "Parang Layang",
          kecamatan: "Bontoala",
        },
      },
      {
        reportType: "biasa",
        title: "Orang terjebak di kamar mandi umum",
        description: "Pintu terkunci dari dalam dan tidak bisa dibuka.",
        location: { lat: -5.132, lng: 119.418, address: "Jl. Bandang" },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Sudah lebih dari 30 menit terkunci.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue30.jpg",
        reporterInfo: {
          name: "Rahman Saleh",
          phone: "081234567885",
          address: "Jl. Bandang No. 4",
          rt: "03",
          rw: "01",
          kelurahan: "Butung",
          kecamatan: "Wajo",
        },
      },
      {
        reportType: "biasa",
        title: "Sampah menumpuk di tepi kanal",
        description: "Mengganggu aliran air dan menimbulkan bau.",
        location: { lat: -5.135, lng: 119.411, address: "Jl. Cendrawasih" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Perlu pembersihan oleh petugas lingkungan.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue31.jpg",
        reporterInfo: {
          name: "Samsul Alam",
          phone: "081234567886",
          address: "Jl. Cendrawasih No. 12",
          rt: "04",
          rw: "02",
          kelurahan: "Tamalabba",
          kecamatan: "Ujung Tanah",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran pasar tradisional",
        description: "Api berasal dari kios makanan.",
        location: { lat: -5.148, lng: 119.443, address: "Pasar Daya" },
        fireType: "pasar",
        hasCasualties: false,
        urgencyLevel: "kritis",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire26.jpg",
        reporterInfo: {
          name: "Nurhaliza",
          phone: "081234567887",
          address: "Jl. Daya Baru No. 6",
          rt: "01",
          rw: "02",
          kelurahan: "Daya",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Hewan ternak terperosok ke lubang",
        description: "Seekor sapi jatuh ke lubang galian proyek.",
        location: { lat: -5.145, lng: 119.435, address: "Jl. Racing Center" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Tidak bisa keluar tanpa bantuan alat berat.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue32.jpg",
        reporterInfo: {
          name: "Budi Hartono",
          phone: "081234567888",
          address: "Jl. Racing Center No. 3",
          rt: "03",
          rw: "03",
          kelurahan: "Kunjung Mae",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Kabel listrik putus dan menjuntai",
        description: "Kabel putus setelah hujan deras dan angin kencang.",
        location: { lat: -5.127, lng: 119.429, address: "Jl. Sultan Alauddin" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Berbahaya bagi pengguna jalan.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue33.jpg",
        reporterInfo: {
          name: "Murniati",
          phone: "081234567889",
          address: "Jl. Sultan Alauddin No. 14",
          rt: "02",
          rw: "01",
          kelurahan: "Mannuruki",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "darurat",
        title: "Kebakaran hutan kecil di pinggiran kota",
        description: "Asap mengepul dari area semak belukar.",
        location: { lat: -5.12, lng: 119.447, address: "Kawasan hutan Antang" },
        fireType: "hutan_lahan",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire27.jpg",
        reporterInfo: {
          name: "Nurdin Basir",
          phone: "081234567890",
          address: "Jl. Antang Raya Blok C",
          rt: "01",
          rw: "04",
          kelurahan: "Antang",
          kecamatan: "Manggala",
        },
      },
      {
        reportType: "darurat",
        title: "Gudang bahan kimia terbakar",
        description: "Asap pekat terlihat dari dalam gudang.",
        location: { lat: -5.13, lng: 119.448, address: "Jl. Kima 5" },
        fireType: "gudang",
        hasCasualties: true,
        urgencyLevel: "kritis",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire28.jpg",
        reporterInfo: {
          name: "Sri Wahyuni",
          phone: "081234567891",
          address: "Jl. Kima 5 Blok E",
          rt: "03",
          rw: "01",
          kelurahan: "Bira",
          kecamatan: "Tamalanrea",
        },
      },
      {
        reportType: "biasa",
        title: "Kucing terjebak di loteng toko",
        description: "Kucing mengeong terus dan tidak bisa turun.",
        location: { lat: -5.136, lng: 119.417, address: "Jl. Pengayoman" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Warga tidak bisa menjangkaunya.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue34.jpg",
        reporterInfo: {
          name: "Julianti",
          phone: "081234567892",
          address: "Jl. Pengayoman No. 9",
          rt: "02",
          rw: "04",
          kelurahan: "Masale",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Pohon tumbang menutup jalan",
        description: "Akibat hujan deras dan angin kencang.",
        location: { lat: -5.138, lng: 119.423, address: "Jl. Landak Baru" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Mengganggu arus lalu lintas.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue35.jpg",
        reporterInfo: {
          name: "Zulkifli",
          phone: "081234567893",
          address: "Jl. Landak Baru No. 15",
          rt: "01",
          rw: "03",
          kelurahan: "Tamalabba",
          kecamatan: "Ujung Tanah",
        },
      },
      {
        reportType: "darurat",
        title: "SPBU terbakar saat pengisian",
        description: "Ledakan kecil terdengar dari area pengisian.",
        location: {
          lat: -5.134,
          lng: 119.421,
          address: "Jl. Perintis Kemerdekaan",
        },
        fireType: "spbu",
        hasCasualties: true,
        urgencyLevel: "kritis",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire29.jpg",
        reporterInfo: {
          name: "Irwan Hasyim",
          phone: "081234567894",
          address: "Jl. Perintis No. 27",
          rt: "03",
          rw: "02",
          kelurahan: "Daya",
          kecamatan: "Biringkanaya",
        },
      },
      {
        reportType: "biasa",
        title: "Orang terjebak dalam lift gedung",
        description: "Lift tidak bisa dibuka dari luar maupun dalam.",
        location: { lat: -5.142, lng: 119.42, address: "Jl. A.P. Pettarani" },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Ada 3 orang di dalam lift.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue36.jpg",
        reporterInfo: {
          name: "Yani Latif",
          phone: "081234567895",
          address: "Jl. A.P. Pettarani No. 21",
          rt: "04",
          rw: "02",
          kelurahan: "Karampuang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Toko elektronik terbakar malam hari",
        description: "Api berasal dari dalam toko, diduga korsleting.",
        location: { lat: -5.133, lng: 119.436, address: "Jl. Ratulangi" },
        fireType: "ruko_toko",
        hasCasualties: false,
        urgencyLevel: "tinggi",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire30.jpg",
        reporterInfo: {
          name: "Nadia Pratiwi",
          phone: "081234567896",
          address: "Jl. Ratulangi No. 4",
          rt: "01",
          rw: "01",
          kelurahan: "Mamajang",
          kecamatan: "Mamajang",
        },
      },
      {
        reportType: "biasa",
        title: "Pipa air PDAM bocor deras",
        description: "Air menyembur ke jalan raya.",
        location: { lat: -5.14, lng: 119.429, address: "Jl. Toddopuli Raya" },
        rescueType: "layanan_lingkungan_dan_fasilitas_umum",
        category: "layanan_lingkungan_dan_fasilitas_umum",
        additionalInfo: "Banjir di sekitar lokasi.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue37.jpg",
        reporterInfo: {
          name: "Hasanuddin",
          phone: "081234567897",
          address: "Jl. Toddopuli No. 5",
          rt: "02",
          rw: "04",
          kelurahan: "Borong",
          kecamatan: "Manggala",
        },
      },
      {
        reportType: "biasa",
        title: "Kambing terperosok di got",
        description: "Kambing milik warga jatuh ke saluran air.",
        location: { lat: -5.139, lng: 119.416, address: "Jl. Cakalang" },
        rescueType: "evakuasi_penyelamatan_hewan",
        category: "evakuasi_penyelamatan_hewan",
        additionalInfo: "Tidak bisa naik sendiri.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue38.jpg",
        reporterInfo: {
          name: "Baharuddin",
          phone: "081234567898",
          address: "Jl. Cakalang No. 18",
          rt: "03",
          rw: "03",
          kelurahan: "Pampang",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "darurat",
        title: "Gedung perkantoran terbakar lantai atas",
        description: "Asap dan api terlihat dari lantai 5.",
        location: { lat: -5.146, lng: 119.415, address: "Jl. Urip Sumoharjo" },
        fireType: "gedung_bertingkat",
        hasCasualties: false,
        urgencyLevel: "kritis",
        rescueType: "kebakaran",
        category: "kebakaran",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/fire31.jpg",
        reporterInfo: {
          name: "Fadli Anwar",
          phone: "081234567899",
          address: "Jl. Urip Sumoharjo No. 16",
          rt: "01",
          rw: "02",
          kelurahan: "Karuwisi",
          kecamatan: "Panakkukang",
        },
      },
      {
        reportType: "biasa",
        title: "Tangga rumah warga ambruk",
        description: "Tangga kayu tua roboh saat dipijak.",
        location: { lat: -5.128, lng: 119.414, address: "Jl. Barukang" },
        rescueType: "penyelamatan_non_hewan_dan_bantuan_teknis",
        category: "penyelamatan_non_hewan_dan_bantuan_teknis",
        additionalInfo: "Warga terjebak di lantai atas.",
        photoUrl:
          "https://res.cloudinary.com/laporpakimage/image/upload/v1749636468/reports/rescue39.jpg",
        reporterInfo: {
          name: "Riski Ahmad",
          phone: "081234567800",
          address: "Jl. Barukang No. 2",
          rt: "04",
          rw: "01",
          kelurahan: "Tamalabba",
          kecamatan: "Ujung Tanah",
        },
      },
    ];
    const skippedReports = [];
    const insertedReports = [];
    for (const report of reports) {
      const exist = await Report.findOne({
        title: report.title,
        "location.address": report.location.address,
      });

      if (exist) {
        skippedReports.push(report.title);
        continue;
      }

      const newReport = new Report({ ...report });
      await newReport.save();
      insertedReports.push(report.title);
    }

    console.log(`✅ ${insertedReports.length} reports successfully inserted.`);
    if (skippedReports.length > 0) {
      console.log(
        `⚠️ ${skippedReports.length} reports skipped (already exist):`
      );
      skippedReports.forEach((title) => console.log(`- ${title}`));
    }
  } catch (error) {
    console.error("Error seeding reports:", error);
  }
}
